# 服务端口
server:
  port: 8002

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Actuator配置,使用'*'开启所有端点,也可以使用['info','env']方式开放指定端点
## refresh 开启配置动态刷新端点
management:
  endpoints:
    web:
      exposure:
        # ['info', 'env', 'health', 'refresh', 'hystrix.stream', 'bus-refresh']
        include: '*'

# Controller/Service/Repository日志开关
kim:
  log:
    enabled: true

# Swagger相关参数配置
swagger:
  title: 消费者服务
  description: 消费provider提供的服务
  base-package: com.kimzing.consumer.web
  base-path: /**
  exclude-path: /error, /ops/**