# 服务端口
server:
  port: 8001

# 数据源配置
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  # Flyway版本控制
  flyway:
    locations: classpath:/db
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/provider?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      # 连接的默认自动提交行为
      auto-commit: true
      # 等待池中连接的最大毫秒数,超过这个时长还没可用的连接则发生SQLException,默认值: 30000(30秒)
      connection-timeout: 30000
      # 允许连接在池中空闲的最长时间,默认值: 600000(10分钟),允许的最小值为10000毫秒(10秒)
      idle-timeout: 600000
      # 连接的最大生命周期, 超时而且没被使用则被释放, 默认值：1800000（30分钟）
      max-lifetime: 1800000
      # 最小空闲连接数,不建议配置，默认值：与maximumPoolSize相同
      minimum-idle: ${spring.datasource.hikari.maximum-pool-size}
      # 允许连接池的最大连接数，包括空闲和正在使用的连接。默认值：10, 推荐的公式：((core_count*2)+effective_spindle_count)，disks in a RAID
      maximum-pool-size: 10
      # 连接只读数据库时配置为true，保证安全
      read-only: false

# Actuator配置,使用'*'开启所有端点,也可以使用['info','env']方式开放指定端点
## refresh 开启配置动态刷新端点
management:
  endpoints:
    web:
      exposure:
        include: ['info', 'env', 'health', 'refresh', 'bus-refresh']

#测试属性动态刷新,需要开启'refresh'端点,同时类上使用@RefreshScope进行注解
config:
  version: v1

# Controller/Service/Repository日志开关
king:
  log:
    enabled: true

# Swagger相关参数配置
swagger:
  title: 生产者服务
  description: 提供给Consumer使用
  base-package: com.kimzing.provider.web
  base-path: /**
  exclude-path: /error, /ops/**

# 下划线转驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true
