#eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.username}:${eureka.password}@node1:7001/eureka/,http://${eureka.username}:${eureka.password}@node2:7002/eureka/,http://${eureka.username}:${eureka.password}@node3:7003/eureka/